version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
  api:
    container_name: three-on-three-api
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RAILS_ENV: development
    volumes:
      - .:/myapp
    depends_on:
      - db
    ports:
      - 3001:3000
    env_file: .env
volumes:
  mysql-data:
    driver: local
